import * as React from 'react';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Card from '@mui/material/Card';
import MuiChip from '@mui/material/Chip';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import { styled } from '@mui/material/styles';

import EdgesensorHighRoundedIcon from '@mui/icons-material/EdgesensorHighRounded';
import ViewQuiltRoundedIcon from '@mui/icons-material/ViewQuiltRounded';
import Spline from '@splinetool/react-spline';
import { Download } from '@mui/icons-material';

const items = [
  {
    icon: <ViewQuiltRoundedIcon />,
    title: 'Blender',
    description1:
      'A spectral‑morphing VST3/AU plugin.',
    description2:
      'Developed in collaboration with the band Polyphia.',
    description3:
      'Featuring a built‑in sample library and seamless Splice integration.',
    description4:
      'Designed for all major DAWs.',
    description5:
      'Inspires new textures, tones, and creative possibilities.',
    imageLight: `url(https://mui.com/static/images/templates/templates-images/dash-light.png")`,
    imageDark: `url(https://mui.com/static/images/templates/templates-images/dash-dark.png")`,
    splineScene: 'https://prod.spline.design/e2jcR3HAeuCfIGXB/scene.splinecode',
    github: 'https://github.com/ColtonOsterlund/blender',
    downloadWindows: "/Blender V4 Installer.exe",
    downloadMac: "/Blender V4 Installer.dmg",
    downloadDemo: "/Blender Demo.mp4",
  },
  {
    icon: <EdgesensorHighRoundedIcon />,
    title: 'MIDI Generator',
    description1:
      'A MIDI‑generation research project using Transformer models and LLMs.',
    description2:
      'Designed specifically for guitar composition.',
    description3:
      'Models musical structure and performance nuance.',
    description4:
      'Focuses on generating expressive chord progressions, riffs, and stylistic patterns.',
    description5:
      'Click the speaker to hear a guitar riff generated by one of the finetuned transformer models.',
    imageLight: `url(https://mui.com/static/images/templates/templates-images/mobile-light.png")`,
    imageDark: `url(https://mui.com/static/images/templates/templates-images/mobile-dark.png")`,
    github: 'https://github.com/ColtonOsterlund/music_generator',
    splineScene: 'https://prod.spline.design/oSTnDOiZoW3vu0K8/scene.splinecode',
    chordProgressionModelNotebook: 'https://colab.research.google.com/drive/1CQsvg08MM_coit_HexZp16pUtdV6s02y?usp=sharing',
    guitarModelNotebook: 'https://colab.research.google.com/drive/1vCSat7rJofHz91fqaxI6vxDLysD9S6-N?usp=sharing',
    downloadDemo: "AI Generated MIDI.mid",
  },
];

interface ChipProps {
  selected?: boolean;
}

const Chip = styled(MuiChip)<ChipProps>(({ theme }) => ({
  variants: [
    {
      props: ({ selected }) => !!selected,
      style: {
        background:
          'linear-gradient(to bottom right, hsl(210, 98%, 48%), hsl(210, 98%, 35%))',
        color: 'hsl(0, 0%, 100%)',
        borderColor: (theme.vars || theme).palette.primary.light,
        '& .MuiChip-label': {
          color: 'hsl(0, 0%, 100%)',
        },
        ...theme.applyStyles('dark', {
          borderColor: (theme.vars || theme).palette.primary.dark,
        }),
      },
    },
  ],
}));

interface MobileLayoutProps {
  descriptionCount: number;
  selectedItemIndex: number;
  handleItemClick: (index: number) => void;
  selectedFeature: (typeof items)[0];
}

export function MobileLayout({
  descriptionCount,
  selectedItemIndex,
  handleItemClick,
  selectedFeature,
}: MobileLayoutProps) {
  if (!items[selectedItemIndex]) {
    return null;
  }

  return (
    <Box
      sx={{
        display: { xs: 'flex', sm: 'none' },
        flexDirection: 'column',
        gap: 2,
      }}
    >
      <Box sx={{ display: 'flex', gap: 2, overflow: 'auto' }}>
        {items.map(({ title }, index) => (
          <Chip
            size="medium"
            key={index}
            label={title}
            onClick={() => handleItemClick(index)}
            selected={selectedItemIndex === index}
          />
        ))}
      </Box>
      <Card variant="outlined">
        <Box sx={{ px: 2, pb: 2 }}>
          <Typography
            gutterBottom
            sx={{ color: 'text.primary', fontWeight: 'medium' }}
          >
            {selectedFeature.title}
          </Typography>
          <Box sx={{ display: 'grid', position: 'relative' }}>
            <Typography variant="body2" sx={{ color: 'text.secondary', gridArea: '1 / 1', opacity: descriptionCount === 0 ? 1 : 0, transition: 'opacity 0.6s ease', }}>
              {selectedFeature.description1}
            </Typography>
            <Typography variant="body2" sx={{ color: 'text.secondary', gridArea: '1 / 1', opacity: descriptionCount === 1 ? 1 : 0, transition: 'opacity 0.6s ease', }}>
              {selectedFeature.description2}
            </Typography>
            <Typography variant="body2" sx={{ color: 'text.secondary', gridArea: '1 / 1', opacity: descriptionCount === 2 ? 1 : 0, transition: 'opacity 0.6s ease', }}>
              {selectedFeature.description3}
            </Typography>
            <Typography variant="body2" sx={{ color: 'text.secondary', gridArea: '1 / 1', opacity: descriptionCount === 3 ? 1 : 0, transition: 'opacity 0.6s ease', }}>
              {selectedFeature.description4}
            </Typography>
            <Typography variant="body2" sx={{ color: 'text.secondary', gridArea: '1 / 1', opacity: descriptionCount === 4 ? 1 : 0, transition: 'opacity 0.6s ease', }}>
              {selectedFeature.description5}
            </Typography>
          </Box>
        </Box>
        <Box
          sx={{
            width: '100%',
            height: 500,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            mt: 1,
          }}
        >
          {items[selectedItemIndex].splineScene && (
            <Spline
              scene={items[selectedItemIndex].splineScene}
              style={{
                width: '100%',
                height: '100%',
              }}
            />
          )}
        </Box>
        <Box
          sx={{
            display: 'flex',
            gap: 2,
            justifyContent: 'center',
            mt: 1,
          }}
        >
          {items[selectedItemIndex].github && (
            <Button
              variant="contained"
              color="primary"
              href={items[selectedItemIndex].github}
              target="_blank"
            >
              GitHub
            </Button>
          )}
        </Box>
      </Card>
    </Box>
  );
}

export default function Projects() {
  const [descriptionCount, setDescriptionCount] = React.useState(0);
  const [selectedItemIndex, setSelectedItemIndex] = React.useState(0);

  React.useEffect(() => {
    const interval = setInterval(() => {
      setDescriptionCount(prev => (prev + 1) % 5);
    }, 3000);

    return () => clearInterval(interval);
  }, []);

  const handleItemClick = (index: number) => {
    setSelectedItemIndex(index);
  };

  const selectedFeature = items[selectedItemIndex];

  return (
    <Container id="projects" sx={{ py: { xs: 8, sm: 16 } }}>
      <Box sx={{ width: { sm: '100%', md: '60%' } }}>
        <Typography
          component="h2"
          variant="h4"
          gutterBottom
          sx={{ color: 'text.primary' }}
        >
          Personal Projects
        </Typography>
        <Typography
          variant="body1"
          sx={{ color: 'text.secondary', mb: { xs: 2, sm: 4 } }}
        >
          My personal projects are a reflection of my passions outside of programming, focusing on software for music production.
        </Typography>
      </Box>
      <Box
        sx={{
          display: 'flex',
          flexDirection: { xs: 'column', md: 'row-reverse' },
          gap: 2,
        }}
      >
        <div>
          <Box
            sx={{
              display: { xs: 'none', sm: 'flex' },
              flexDirection: 'column',
              gap: 2,
              height: '100%',
            }}
          >
            {items.map(({ icon, title, description1, description2, description3, description4, description5 }, index) => (
              <Box
                key={index}
                component={Button}
                onClick={() => handleItemClick(index)}
                sx={[
                  (theme) => ({
                    p: 2,
                    height: '100%',
                    width: '100%',
                    '&:hover': {
                      backgroundColor: (theme.vars || theme).palette.action.hover,
                    },
                  }),
                  selectedItemIndex === index && {
                    backgroundColor: 'action.selected',
                  },
                ]}
              >
                <Box
                  sx={[
                    {
                      width: '100%',
                      display: 'flex',
                      flexDirection: 'column',
                      alignItems: 'left',
                      gap: 1,
                      textAlign: 'left',
                      textTransform: 'none',
                      color: 'text.secondary',
                    },
                    selectedItemIndex === index && {
                      color: 'text.primary',
                    },
                  ]}
                >
                  {icon}
                  <Typography variant="h6">{title}</Typography>
                  <Box sx={{ display: 'grid', position: 'relative' }}>
                    <Typography variant="body2" sx={{ gridArea: '1 / 1', opacity: descriptionCount === 0 ? 1 : 0, transition: 'opacity 0.6s ease', }}>{description1}</Typography>
                    <Typography variant="body2" sx={{ gridArea: '1 / 1', opacity: descriptionCount === 1 ? 1 : 0, transition: 'opacity 0.6s ease', }}>{description2}</Typography>
                    <Typography variant="body2" sx={{ gridArea: '1 / 1', opacity: descriptionCount === 2 ? 1 : 0, transition: 'opacity 0.6s ease', }}>{description3}</Typography>
                    <Typography variant="body2" sx={{ gridArea: '1 / 1', opacity: descriptionCount === 3 ? 1 : 0, transition: 'opacity 0.6s ease', }}>{description4}</Typography>
                    <Typography variant="body2" sx={{ gridArea: '1 / 1', opacity: descriptionCount === 4 ? 1 : 0, transition: 'opacity 0.6s ease', }}>{description5}</Typography>
                  </Box>
                </Box>
              </Box>
            ))}
          </Box>
          <MobileLayout
            descriptionCount={descriptionCount}
            selectedItemIndex={selectedItemIndex}
            handleItemClick={handleItemClick}
            selectedFeature={selectedFeature}
          />
        </div>
        <Card
          variant="outlined"
          sx={{
            height: '100%',
            width: '100%',
            display: { xs: 'none', sm: 'flex' },
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'flex-start',
            p: 2,
            gap: 2,
          }}
        >

          <Box
            sx={{
              width: '100%',
              height: 500,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >

            {items[selectedItemIndex].splineScene && (
              <Spline
                scene={items[selectedItemIndex].splineScene}
                style={{
                  width: '100%',
                  height: '100%',
                }}
              />
            )}
          </Box>
          <Box
            sx={{
              display: 'flex',
              gap: 2,
              justifyContent: 'center',
              mt: 1,
            }}
          >
            {items[selectedItemIndex].github && (
              <Button
                variant="contained"
                color="primary"
                href={items[selectedItemIndex].github}
                target="_blank"
              >
                GitHub
              </Button>
            )}
            {items[selectedItemIndex].title === "Blender" && (
              <>
                {items[selectedItemIndex].downloadDemo && (
                  <Button
                    variant="outlined"
                    component="a"
                    href={items[selectedItemIndex].downloadDemo}
                    download
                    startIcon={<Download />}
                  >
                    Demo (v4.0)
                  </Button>
                )}
                {items[selectedItemIndex].downloadWindows && (
                  <Button
                    variant="outlined"
                    component="a"
                    href={items[selectedItemIndex].downloadWindows}
                    download
                    startIcon={<Download />}
                  >
                    Windows (v4.0)
                  </Button>
                )}
                {items[selectedItemIndex].downloadMac && (
                  <Button
                    variant="outlined"
                    component="a"
                    href={items[selectedItemIndex].downloadMac}
                    download
                    startIcon={<Download />}
                  >
                    Mac (v4.0)
                  </Button>
                )}
              </>
            )}
            {items[selectedItemIndex].title === "MIDI Generator" && (
              <>
                {items[selectedItemIndex].chordProgressionModelNotebook && (
                  <Button
                    variant="contained"
                    color="primary"
                    href={items[selectedItemIndex].chordProgressionModelNotebook}
                    target="_blank"
                  >
                    Chord Progression Model (v3.0)
                  </Button>
                )}
                {items[selectedItemIndex].guitarModelNotebook && (
                  <Button
                    variant="contained"
                    color="primary"
                    href={items[selectedItemIndex].guitarModelNotebook!}
                    target="_blank"
                  >
                    Guitar Model (v3.0)
                  </Button>
                )}
                {items[selectedItemIndex].downloadDemo && (
                  <Button
                    variant="outlined"
                    component="a"
                    href={items[selectedItemIndex].downloadDemo}
                    download
                    startIcon={<Download />}
                  >
                    Demo (.mid)
                  </Button>
                )}
              </>
            )}
          </Box>
        </Card>
      </Box>
    </Container>
  );
}